Chase:
  email_addresses:
    - no.reply.alerts@chase.com
  accounts:
    - type: credit
      date_opened: 2024-01-01
      date_closed: 2024-12-31
Discover:
  email_addresses:
    - discover@services.discover.com
  accounts:
    - type: credit
      date_opened: 2024-01-01
      date_closed: 2024-12-31
Huntington:
  email_addresses:
    - HuntingtonAlerts@email.huntington.com
    - HuntingtonOnline@email.huntington.com
  accounts:
    - type: liquid
      name: SAVE
      date_opened: 2024-01-01
      date_closed: 2024-12-31
    - type: liquid
      name: CHECK
      date_opened: 2024-01-01
      date_closed: 2024-12-31
