#!/usr/bin/env python3
# ./db_init
import logging
import sqlite3

LOGGER = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    filename="root.log",
    encoding="utf-8",
    format="%(asctime)s:%(levelname)s:%(message)s",
)

connection = sqlite3.connect("sage_db.db")
cursor = connection.cursor()
sql_file = open("schema.sql")
sql_as_str = sql_file.read()
cursor.executescript(sql_as_str)
connection.commit()
cursor.close()
connection.close()
LOGGER.info("Successfully initialized sage_db.db")
