# Run this compose in production. 
services:
  db:
    image: postgres:14.4
    container_name: sage-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      # TODO: Separate the schema and the init data like banks
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - /mnt/sage_db/data:/var/lib/postgresql/data
  mailserver:
    image: sage_mailserver
    container_name: sage-mailserver
    build: ./docker/mailserver/
    restart: always
    env_file:
      - .env
    ports:
      - '25:25'    # SMTP
      - '143:143'  # IMAP4
    volumes:
      - /mnt/sage_mailserver/home/:/home/
      - /mnt/sage_mailserver/var/log/:/var/log/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./docker/mailserver/scripts/postfix_dovecot_config_prod.sh:/postfix_dovecot_config.sh
      - ./docker/mailserver/scripts/dkim_fail2ban_prod.sh:/dkim_fail2ban.sh
  grafana:
    image: grafana/grafana-oss
    container_name: sage-grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - '3000:3000'
    volumes:
      - ./docker/grafana/grafana_dev.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
      - ./docker/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
      # TODO: https://grafana.com/docs/grafana/latest/setup-grafana/set-up-https/#set-up-symlinks-to-grafana
      # Ideally configure grafana to look in /etc/letsencrypt/ for the files
      - /etc/letsencrypt/live/subdomain.mysite.com/privkey.pem /etc/grafana/grafana.key
      - /etc/letsencrypt/live/subdomain.mysite.com/fullchain.pem /etc/grafana/grafana.crt
  nginx:
    image: nginx:latest
    container_name: sage-nginx
    restart: always
    env_file:
      - .env
    # environment:
    #   - NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Initialize env vars in conf.d
      - ./docker/nginx/prod:/etc/nginx/templates
      # TODO: https://medium.com/@vinoji2005/guide-to-setup-lets-encrypt-ssl-in-nginx-be3d641bb58a
      # Configure nginx to look for files in /etc/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/