# Run this compose for local development. 
services:
  db:
    image: postgres:14.4
    container_name: sage-db
    restart: always
    env_file:
      - .env-example
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      # TODO: Separate the schema and the init data like banks
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
  mx:
    image: sage_mx
    container_name: sage-mx
    build: ./docker/mx/
    restart: always
    env_file:
      - .env-example
    ports:
      - '25:25'    # SMTP
      - '143:143'  # IMAP4
    volumes:
      - ./docker/mx/scripts/postfix_dovecot_config_dev.sh:/postfix_dovecot_config.sh
      - ./docker/mx/test_data/:/test_data/
  grafana:
    image: grafana/grafana-oss
    container_name: sage-grafana
    restart: unless-stopped
    env_file:
      - .env-example
    ports:
     - '3000:3000'
    volumes:
      - ./docker/grafana/grafana_dev.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
      - ./docker/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
  nginx:
    image: nginx:latest
    container_name: sage-nginx
    restart: always
    env_file:
      - .env-example
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/dev:/etc/nginx/conf.d
volumes:
  db:
    driver: local
