version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sage/db/init:/docker-entrypoint-initdb.d
  mailserver:
    image: sage_mailserver
    build: ./docker/mailserver/
    expose:
      - '25'
      - '143'
    ports:
      - '25:25'
      - '143:143'
    env_file:
      - .env
    restart: always
    volumes:
      - ./docker/mailserver/scripts/postfix_config_development.sh:/configure.sh
      - ./tests/test_data/:/test_data/
volumes:
  db:
    driver: local