# Run this compose in production. 
services:
  db:
    image: postgres:14.4
    container_name: sage-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      # TODO: Separate the schema and the init data like banks
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - /mnt/sage_db/data:/var/lib/postgresql/data
  mx:
    image: sage_mx
    container_name: sage-mx
    build: ./docker/mx/
    restart: always
    env_file:
      - .env
    ports:
      - '25:25'    # SMTP
      - '143:143'  # IMAP4
    volumes:
      - /mnt/sage_mx/home/:/home/
      - /mnt/sage_mx/var/log/:/var/log/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./docker/mx/scripts/postfix_dovecot_config_prod.sh:/postfix_dovecot_config.sh
      - ./docker/mx/scripts/dkim_fail2ban_prod.sh:/dkim_fail2ban.sh
  grafana:
    image: grafana/grafana-oss
    container_name: sage-grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - '3000:3000'
    volumes:
      - ./docker/grafana/grafana_prod.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
      - ./docker/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
  nginx:
    image: nginx:latest
    container_name: sage-nginx
    restart: always
    env_file:
      - .env
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/prod:/etc/nginx/templates
      - /etc/letsencrypt/:/etc/letsencrypt/