version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sage/db/init:/docker-entrypoint-initdb.d
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
    - "25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
volumes:
  db:
    driver: local