# This is the base docker-compose.yml file,
# used in conjunction with docker-compose.override.yml in development
# or docker-compose.prod.yml in production
version: '3.8'
services:
  db:
    image: postgres:14.4
    container_name: sage-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - db:/var/lib/postgresql/data
      # TODO: Separate the schema and the init data like banks
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
  mailserver:
    image: sage_mailserver
    container_name: sage-mailserver
    build: ./docker/mailserver/
    restart: always
    env_file:
      - .env
    ports:
      - '25:25'    # SMTP
      - '143:143'  # IMAP4
volumes:
  db:
    driver: local