version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sage/db/init:/docker-entrypoint-initdb.d
  postfix:
    image: danilsmirnov/postfix:latest
    expose:
      - '25'
    ports:
      - '25:25'
    env_file:
      - .env
    restart: always
    volumes:
      - ./scripts/postfix_config.sh:/configure.sh
volumes:
  db:
    driver: local