# This file is for production. 
# Run this in conjunction with the base file docker-compose.yml.
services:
  reverse-proxy:
    image: docker.io/traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.mail-smtp.address=:25
    ports:
      - "25:25"
    networks:
      default:
        ipv4_address:  172.16.42.2
  mailserver:
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - '25:25' # SMTP (temporarily opened for troubleshooting)
      - '587:587'  # ESMTP (explicit TLS => STARTTLS)
      - '993:993'  # IMAP4 (implicit TLS)
    volumes:
    # FIXME: Using dev postfix/dovecot config. Do I need separate configs anymore?
    - ./docker/mailserver/scripts/postfix_dovecot_config_dev.sh:/postfix_dovecot_config.sh
    - ./docker/mailserver/scripts/dkim_fail2ban_prod.sh:/dkim_fail2ban.sh
    - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      default:
        ipv4_address:  172.16.42.3

networks:
  custom_network:
    ipam:
      driver: bridge
      config:
        - subnet: "172.16.42.0/24"