[server]
; The IP address to bind to.
; Default is "0.0.0.0", which binds to all interfaces.
bind_address = 

; The HTTP port to use.
; Default is 3000. Port 80 requires root privileges.
http_port = 3000

; The public facing domain name used to access Grafana from a browser.
domain = ${DOMAIN}

; The full public facing URL you use in browser, used for redirects and emails
root_url = %(protocol)s://%(domain)s:%(http_port)s/

; The path of the web application under the domain.
; If the value is not set, then it defaults to "/". Options are anything under a ".". To make your application available under a subpath add a trailing "/" as part of the URL prefix. So if you insert the following:
;   http_prefix = /grafana
; Then if base_url is http://localhost:3000/ then the final URL would be http://localhost:3000/grafana
http_prefix =

; Enables all available web security protections.
; Default is true
# enable_web_security = false

[security]
# This setting controls whether anonymous access to the sign-up page is allowed.
allow_sign_up = false

# This setting controls whether anonymous access to the email verification page is allowed.
allow_anonymous_access_to_email_verification_page = false

# This setting controls whether anonymous access to the password reset page is allowed.
allow_anonymous_access_to_password_reset_page = false

admin_user=${GRAFANA_USER}
admin_password=${GRAFANA_PASSWORD}

# [log.console]
# level = warn