#!/bin/bash
set -e

POSTGRES_PASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER etl WITH PASSWORD '$POSTGRES_ETL_PASSWORD';
	GRANT pg_read_all_data TO etl;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO etl;
	-- automatically grant INSERT on future tables
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO etl;

	CREATE USER grafanareader WITH PASSWORD '$POSTGRES_GRAFANA_PASSWORD';
	GRANT USAGE ON SCHEMA public TO grafanareader;
	GRANT pg_read_all_data TO grafanareader;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafanareader;
EOSQL