- hosts: localhost
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ephem_name: '{{ lookup("env", "EPHEM_NAME") }}'

  tasks:
  - name: Delete the new droplet
    digital_ocean_droplet:
      oauth_token: "{{ digital_ocean_token }}"
      name: "{{ ephem_name }}"
      unique_name: yes
      state: absent
      wait_timeout: 600
    with_inventory_hostnames:
      - web
    register: droplet_result

  - name: Delete the firewall
    community.digitalocean.digital_ocean_firewall:
      oauth_token: "{{ digital_ocean_token }}"
      name: "{{ ephem_name }}"
      state: absent