- hosts: localhost
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ephem_name: '{{ lookup("env", "EPHEM_NAME") }}'
  tasks:
  - name: Get all SSH keys info
    digital_ocean_sshkey_info:
      oauth_token: "{{ digital_ocean_token }}"
    register: sshkey_info

  - name: Show SSH keys
    ansible.builtin.debug:
      msg:
      - "{{ sshkey_info.data }}"

  - name: Find the ID of the ephemeral SSH Key named {{ ephem_name }}
    set_fact:
      ephem_sshkey: "{{ sshkey_info.data | json_query(query) }}"
    vars:
      query: "[?name=='{{  ephem_name  }}'] | [0]"

  - name: Delete the SSH key named {{ ephem_name }}
    digital_ocean_sshkey:
      oauth_token: "{{ digital_ocean_token }}"
      fingerprint: "{{ ephem_sshkey.fingerprint }}"
      state: absent
    register: sshkey_result

  - name: Delete the Droplet named {{ ephem_name }}
    digital_ocean_droplet:
      oauth_token: "{{ digital_ocean_token }}"
      name: "{{ ephem_name }}"
      unique_name: true
      wait_timeout: 600
      state: absent
    register: droplet_result

  - name: Delete the firewall named {{ ephem_name }}
    community.digitalocean.digital_ocean_firewall:
      oauth_token: "{{ digital_ocean_token }}"
      name: "{{ ephem_name }}"
      state: absent