- hosts: localhost
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ephem_name: '{{ lookup("env", "EPHEM_NAME") }}'

  tasks:
  
  - name: Delete the new droplet
    digital_ocean_droplet:
      state: absent
      name: "{{ ephem_name }}"
      oauth_token: "{{ digital_ocean_token }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]
    with_inventory_hostnames:
      - web
    register: droplet_result

  - name: Gather firewall information by name
    community.digitalocean.digital_ocean_firewall_info:
      oauth_token: "{{ oauth_token }}"
      name: "{{ ephem_name }}"
    register: firewall_info

  - name: Delete the firewall
    community.digitalocean.digital_ocean_firewall:
      state: absent
      oauth_token: "{{ oauth_token }}"
      id: "{{ firewall_info.firewalls[0].id }}"
    when: firewall_info.firewalls | length > 0