# - name: Create a droplet named "sageEphem"
#   import_playbook: imported_playbooks/create_droplet_ephem.yml

- name: Configure the droplet "sageEphem"
  import_playbook: imported_playbooks/configure_droplet_ephem.yml