- name: Create a droplet named "sageEphem"
  import_playbook: imported_playbooks/create_droplet_ephem.yml

- name: Configure the droplet "sageEphem" as root
  import_playbook: imported_playbooks/configure_droplet_as_root.yml
  vars:
    host_name: 'sageEphem'
    ssh_private_key_file_path: '{{ lookup("env", "EPHEM_SSH_PRIVATE_KEY_FILE_PATH") }}'
    ssh_public_key: '{{ lookup("env", "EPHEM_SSH_PUBLIC_KEY") }}'

- name: Configure the droplet "sageEphem" as user 
  import_playbook: imported_playbooks/configure_droplet_as_user.yml
  vars:
    host_name: 'sageEphem'
    ssh_private_key_file_path: '{{ lookup("env", "EPHEM_SSH_PRIVATE_KEY_FILE_PATH") }}'
    ssh_public_key: '{{ lookup("env", "EPHEM_SSH_PUBLIC_KEY") }}'
