#!/bin/bash
set -e

POSTGRES_PASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER etl;
	ALTER USER etl WITH PASSWORD '$POSTGRES_ETL_PASSWORD';
EOSQL