#!/bin/bash
set -e

POSTGRES_PASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER etl;
	ALTER USER etl WITH PASSWORD '$POSTGRES_ETL_PASSWORD';
	GRANT pg_read_all_data TO etl;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO etl;
	-- automatically grant INSERT on future tables
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON TABLES TO etl;

EOSQL