#!/usr/bin/env python3
# ./db_init
import sqlite3

connection = sqlite3.connect("sage_db.db")
cursor = connection.cursor()
sql_file = open("schema.sql")
sql_as_str = sql_file.read()
cursor.executescript(sql_as_str)
connection.commit()
cursor.close()
connection.close()
print("Successfully initialized sage_db.db")
