- hosts: localhost
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ephemeral_ssh_key_pub: '{{ lookup("env", "EPHEMERAL_SSH_KEY_PUB") }}'
    ephemeral_ssh_private_key_file: '{{ lookup("env", "EPHEMERAL_SSH_PRIVATE_KEY_FILE") }}'
    droplet_size: s-1vcpu-1gb
    droplet_region: nyc1
    droplet_image: ubuntu-22-04-x64
  tasks:
  
  - name: Add public ssh key to Digital Ocean account
    digital_ocean_sshkey:
      name: "Personal Projects - Local"
      oauth_token: "{{ digital_ocean_token }}"
      ssh_pub_key: "{{ ephemeral_ssh_key_pub }}"
      state: present
    register: sshkey_result

  - name: Create a new Droplet
    digital_ocean_droplet:
      name: sage.ephemeral
      oauth_token: "{{ digital_ocean_token }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]      
      state: present
    with_inventory_hostnames:
      - web
    register: droplet_result

  # TODO: Abstract the file path or do something different to show the IP address
  - name: Save IP and host name to ./ansible/droplet_hosts
    become: yes
    lineinfile:
      path: /home/kfike/Projects/sage/ansible/droplet_hosts
      regexp: '.*{{ item.data.droplet.name }}$'
      line: "{{ item.data.droplet.networks.v4[0].ip_address }}  {{ item.data.droplet.name }}"
    with_items: "{{ droplet_result.results }}"

  - name: Delete the new droplet
    digital_ocean_droplet:
      state: absent
      name: sage.ephemeral
      oauth_token: "{{ digital_ocean_token }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]
    with_inventory_hostnames:
      - web
    register: droplet_result