- hosts: localhost
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    prod_ssh_key_pub: '{{ lookup("env", "PROD_SSH_KEY_PUB") }}'
    prod_ssh_private_key_file: '{{ lookup("env", "PROD_SSH_PRIVATE_KEY_FILE") }}'
    droplet_size: s-1vcpu-1gb
    droplet_region: nyc1
    droplet_image: ubuntu-22-04-x64
  tasks:
  
  - name: add public ssh key to digitalocean account
    digital_ocean_sshkey:
      name: "Personal Projects - Local"
      oauth_token: "{{ digital_ocean_token }}"
      ssh_pub_key: "{{ prod_ssh_key_pub }}"
      state: present
    register: sshkey_result

  - name: create a new droplet assigning the key
    digital_ocean_droplet:
      name: sage.prod
      oauth_token: "{{ digital_ocean_token }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]      
      state: present
    with_inventory_hostnames:
      - web
    register: droplet_result

  - name: save ip and hostname to local hosts file
    become: yes
    lineinfile:
      path: /home/kfike/Projects/sage/ansible/droplet_hosts
      regexp: '.*{{ item.data.droplet.name }}$'
      line: "{{ item.data.droplet.networks.v4[0].ip_address }}  {{ item.data.droplet.name }}"
    with_items: "{{ droplet_result.results }}"