- hosts: sageEphem
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ansible_user: '{{ lookup("env", "SERVER_USER") }}'
  tasks:
      - name: Clone the GitLab repository
        git:
          repo: 'https://github.com/katefike/sage.git'
          dest: '/home/kfike/sage/'
          clone: yes
          update: yes