- hosts: sageEphem
  vars:
    digital_ocean_token: '{{ lookup("env", "DO_API_TOKEN") }}'
    ansible_ssh_private_key_file: '{{ lookup("env", "EPHEM_SSH_KEY_FILE_PRIV") }}'
    ephem_ssh_key_pub: '{{ lookup("env", "EPHEM_SSH_KEY_PUB") }}'
    server_user: '{{ lookup("env", "SERVER_USER") }}'
    server_user_password: '{{ lookup("env", "SERVER_USER_PASSWORD") }}'
    ansible_user: '{{ server_user }}'
  tasks:
      - name: DEBUG
        script: ls -a 
        register: out

      - debug: var=out.stdout_lines
    # - name: Clone the GitLab repository
    #   git:
    #     repo: 'https://github.com/katefike/sage.git'
    #     dest: '/home/sage/'
    #     clone: yes
    #     update: yes