name: Pull Request or Push to Development

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Copy the .env-example file.
      run: cp .env-example .env
    - name: Start docker containers
      env:
          QA_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
      run: docker-compose up --build -d
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check for running docker containers
      env:
          QA_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
      run: docker ps
    - name: Test with pytest
      env:
          QA_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
      run: pytest tests/test_action/
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics\
    - name: Dump Docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2.2.0
